# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit.ui'
#
# Created: Mon Mar 18 16:13:58 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_editDialog(object):
    def setupUi(self, editDialog):
        editDialog.setObjectName(_fromUtf8("editDialog"))
        editDialog.setEnabled(True)
        editDialog.resize(400, 346)
        self.gridLayout = QtGui.QGridLayout(editDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.textDownloadPath = QtGui.QLineEdit(editDialog)
        self.textDownloadPath.setEnabled(False)
        self.textDownloadPath.setObjectName(_fromUtf8("textDownloadPath"))
        self.gridLayout.addWidget(self.textDownloadPath, 9, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(editDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 13, 1, 1, 1)
        self.labelInstallPath = QtGui.QLabel(editDialog)
        self.labelInstallPath.setEnabled(False)
        self.labelInstallPath.setObjectName(_fromUtf8("labelInstallPath"))
        self.gridLayout.addWidget(self.labelInstallPath, 10, 0, 1, 1)
        self.labelLanguage = QtGui.QLabel(editDialog)
        self.labelLanguage.setObjectName(_fromUtf8("labelLanguage"))
        self.gridLayout.addWidget(self.labelLanguage, 1, 0, 1, 1)
        self.labelSize = QtGui.QLabel(editDialog)
        self.labelSize.setEnabled(False)
        self.labelSize.setObjectName(_fromUtf8("labelSize"))
        self.gridLayout.addWidget(self.labelSize, 8, 0, 1, 1)
        self.textLanguage = QtGui.QLineEdit(editDialog)
        self.textLanguage.setObjectName(_fromUtf8("textLanguage"))
        self.gridLayout.addWidget(self.textLanguage, 1, 1, 1, 1)
        self.textInstallPath = QtGui.QLineEdit(editDialog)
        self.textInstallPath.setEnabled(False)
        self.textInstallPath.setObjectName(_fromUtf8("textInstallPath"))
        self.gridLayout.addWidget(self.textInstallPath, 10, 1, 1, 1)
        self.labelURL = QtGui.QLabel(editDialog)
        self.labelURL.setEnabled(False)
        self.labelURL.setObjectName(_fromUtf8("labelURL"))
        self.gridLayout.addWidget(self.labelURL, 11, 0, 1, 1)
        self.labelDownloadPath = QtGui.QLabel(editDialog)
        self.labelDownloadPath.setEnabled(False)
        self.labelDownloadPath.setObjectName(_fromUtf8("labelDownloadPath"))
        self.gridLayout.addWidget(self.labelDownloadPath, 9, 0, 1, 1)
        self.textInstalledDate = QtGui.QLineEdit(editDialog)
        self.textInstalledDate.setEnabled(False)
        self.textInstalledDate.setObjectName(_fromUtf8("textInstalledDate"))
        self.gridLayout.addWidget(self.textInstalledDate, 12, 1, 1, 1)
        self.labelPackageName = QtGui.QLabel(editDialog)
        self.labelPackageName.setObjectName(_fromUtf8("labelPackageName"))
        self.gridLayout.addWidget(self.labelPackageName, 0, 0, 1, 1)
        self.labelVersion = QtGui.QLabel(editDialog)
        self.labelVersion.setObjectName(_fromUtf8("labelVersion"))
        self.gridLayout.addWidget(self.labelVersion, 2, 0, 1, 1)
        self.textSize = QtGui.QLineEdit(editDialog)
        self.textSize.setEnabled(False)
        self.textSize.setObjectName(_fromUtf8("textSize"))
        self.gridLayout.addWidget(self.textSize, 8, 1, 1, 1)
        self.textPackageName = QtGui.QLineEdit(editDialog)
        self.textPackageName.setObjectName(_fromUtf8("textPackageName"))
        self.gridLayout.addWidget(self.textPackageName, 0, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(editDialog)
        self.checkBox.setChecked(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 13, 0, 1, 1)
        self.labelInstalledDate = QtGui.QLabel(editDialog)
        self.labelInstalledDate.setEnabled(False)
        self.labelInstalledDate.setObjectName(_fromUtf8("labelInstalledDate"))
        self.gridLayout.addWidget(self.labelInstalledDate, 12, 0, 1, 1)
        self.textVersion = QtGui.QLineEdit(editDialog)
        self.textVersion.setObjectName(_fromUtf8("textVersion"))
        self.gridLayout.addWidget(self.textVersion, 2, 1, 1, 1)
        self.textURL = QtGui.QLineEdit(editDialog)
        self.textURL.setEnabled(False)
        self.textURL.setObjectName(_fromUtf8("textURL"))
        self.gridLayout.addWidget(self.textURL, 11, 1, 1, 1)
        self.line = QtGui.QFrame(editDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 7, 0, 1, 2)
        self.checkBoxFavourite = QtGui.QCheckBox(editDialog)
        self.checkBoxFavourite.setObjectName(_fromUtf8("checkBoxFavourite"))
        self.gridLayout.addWidget(self.checkBoxFavourite, 5, 0, 1, 1)

        self.retranslateUi(editDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), editDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), editDialog.reject)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.labelInstalledDate.setEnabled)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.textInstalledDate.setEnabled)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.labelURL.setEnabled)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.textURL.setEnabled)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.labelInstallPath.setEnabled)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.textInstallPath.setEnabled)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.labelDownloadPath.setEnabled)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.labelSize.setEnabled)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.textDownloadPath.setEnabled)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.textSize.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(editDialog)
        editDialog.setTabOrder(self.textPackageName, self.textLanguage)
        editDialog.setTabOrder(self.textLanguage, self.textVersion)
        editDialog.setTabOrder(self.textVersion, self.checkBoxFavourite)
        editDialog.setTabOrder(self.checkBoxFavourite, self.textSize)
        editDialog.setTabOrder(self.textSize, self.textDownloadPath)
        editDialog.setTabOrder(self.textDownloadPath, self.textInstallPath)
        editDialog.setTabOrder(self.textInstallPath, self.textURL)
        editDialog.setTabOrder(self.textURL, self.textInstalledDate)
        editDialog.setTabOrder(self.textInstalledDate, self.checkBox)
        editDialog.setTabOrder(self.checkBox, self.buttonBox)

    def retranslateUi(self, editDialog):
        editDialog.setWindowTitle(QtGui.QApplication.translate("editDialog", "Edit Package Details", None, QtGui.QApplication.UnicodeUTF8))
        self.textDownloadPath.setToolTip(QtGui.QApplication.translate("editDialog", "<html><head/><body><p>The location that the package is downloaded to.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInstallPath.setText(QtGui.QApplication.translate("editDialog", "Install Path", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLanguage.setText(QtGui.QApplication.translate("editDialog", "Language", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSize.setText(QtGui.QApplication.translate("editDialog", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.textLanguage.setToolTip(QtGui.QApplication.translate("editDialog", "<html><head/><body><p>The language of the package.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.textInstallPath.setToolTip(QtGui.QApplication.translate("editDialog", "<html><head/><body><p>The location that the package is installed to.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelURL.setText(QtGui.QApplication.translate("editDialog", "URL", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDownloadPath.setText(QtGui.QApplication.translate("editDialog", "Download Path", None, QtGui.QApplication.UnicodeUTF8))
        self.textInstalledDate.setToolTip(QtGui.QApplication.translate("editDialog", "<html><head/><body><p>The date that the package was installed on.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPackageName.setText(QtGui.QApplication.translate("editDialog", "Package Name", None, QtGui.QApplication.UnicodeUTF8))
        self.labelVersion.setText(QtGui.QApplication.translate("editDialog", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.textSize.setToolTip(QtGui.QApplication.translate("editDialog", "<html><head/><body><p>The size of the package (in kilobytes)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.textPackageName.setToolTip(QtGui.QApplication.translate("editDialog", "<html><head/><body><p>The name of the package.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setToolTip(QtGui.QApplication.translate("editDialog", "<html><head/><body><p>Allowing the editing of advanced details.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("editDialog", "Enable advanced details", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInstalledDate.setText(QtGui.QApplication.translate("editDialog", "Installed Date", None, QtGui.QApplication.UnicodeUTF8))
        self.textVersion.setToolTip(QtGui.QApplication.translate("editDialog", "<html><head/><body><p>The version of the software package.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.textURL.setToolTip(QtGui.QApplication.translate("editDialog", "<html><head/><body><p>The URL that the package was downloaded from.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxFavourite.setToolTip(QtGui.QApplication.translate("editDialog", "<html><head/><body><p>Mark the package as being a favourite.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxFavourite.setText(QtGui.QApplication.translate("editDialog", "Favourite", None, QtGui.QApplication.UnicodeUTF8))

